POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "wolfgang",
    "password": "1230"
}
#######
DELETE http://localhost:8080/users?id=afwioj
Authorization: qrt5tiwybmj

#######
GET http://localhost:8080/users?name=wolf
Authorization: kzj1b6htsbf

#######
GET http://localhost:8080/systemInfo

#######
PUT http://localhost:8080/users
Authorization: 6q08pl057r
Content-Type: application/json

{
    "age": "34",
    "email": "w@cherry.com",
    "name": "uwe",
    "workingPosition": 3
}